### ISSUE TITLE
Better Crop/Review screen title

### ISSUE THREAD

**Issue by dbotha** [OceanLabs/Android-Print-SDK#11]
Currently the title is the product/device name which is not great (see my very bad photo of the screen -- sorry quickest route to getting a "screenshot"). This might be bettered titled "Position Photo"

![img_3822](https://cloud.githubusercontent.com/assets/760653/8801490/03123eec-2fb3-11e5-8434-2c9e243e99d2.JPG)

**Comment by ghost** [comment]
I had a conversation about this before - I guess if not with you then Dan. The problem is that "Reposition the Photo" - as it has on the iOS version - isn't a title, it's an instruction. It doesn't really look right on an Android device. Perhaps some sort of hint text in a banner that animates away after a few seconds would work?

**Comment by dbotha** [comment]
Cool makes sense -- I'll leave it to you to follow up with dan for what you need.
