### ISSUE TITLE
MissingResourceException

### ISSUE THREAD

**Issue by herbig** [OceanLabs/Android-Print-SDK#46]

**Comment by ghost** [comment]
Are you setting the locale manually? I can't find any country 
corresponding to the country code "LG"; could you explain what locale 
you are using, i.e. language ("es" = Spanish?), and country?

**Comment by herbig** [comment]
This crash was from a user, so I'm not entirely sure how they got that locale, 

I found this, which appears to have had the same issue, but no real explanation:

https://github.com/codinguser/gnucash-android/search?utf8=%E2%9C%93&q=es_LG

**Comment by sarahcyates** [comment]
This is an odd one, because fundamentally es_LG is not a valid Android language/location combination,  in fact LG is not a recognised ISO Alpha-2 location code to begin with, so I'm not sure how it's being produced, it could be the case that Samsung mapped something incorrectly and this is at it's core, a Samsung bug, in which case we can put a similar exception into the code.

**Comment by sarahcyates** [comment]
Fixed in 5.8.7.

Now it does the same check as the example above - if it sees es_LG as a locale, it maps it to es_ES instead. Hopefully this will avoid this problem occurring, if it does, feel free to reopen the issue.
